// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/eebus-go/api"
	api0 "github.com/enbility/ship-go/api"
	mock "github.com/stretchr/testify/mock"
)

// NewServiceReaderInterface creates a new instance of ServiceReaderInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceReaderInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceReaderInterface {
	mock := &ServiceReaderInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ServiceReaderInterface is an autogenerated mock type for the ServiceReaderInterface type
type ServiceReaderInterface struct {
	mock.Mock
}

type ServiceReaderInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceReaderInterface) EXPECT() *ServiceReaderInterface_Expecter {
	return &ServiceReaderInterface_Expecter{mock: &_m.Mock}
}

// RemoteSKIConnected provides a mock function for the type ServiceReaderInterface
func (_mock *ServiceReaderInterface) RemoteSKIConnected(service api.ServiceInterface, ski string) {
	_mock.Called(service, ski)
	return
}

// ServiceReaderInterface_RemoteSKIConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteSKIConnected'
type ServiceReaderInterface_RemoteSKIConnected_Call struct {
	*mock.Call
}

// RemoteSKIConnected is a helper method to define mock.On call
//   - service api.ServiceInterface
//   - ski string
func (_e *ServiceReaderInterface_Expecter) RemoteSKIConnected(service interface{}, ski interface{}) *ServiceReaderInterface_RemoteSKIConnected_Call {
	return &ServiceReaderInterface_RemoteSKIConnected_Call{Call: _e.mock.On("RemoteSKIConnected", service, ski)}
}

func (_c *ServiceReaderInterface_RemoteSKIConnected_Call) Run(run func(service api.ServiceInterface, ski string)) *ServiceReaderInterface_RemoteSKIConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceInterface
		if args[0] != nil {
			arg0 = args[0].(api.ServiceInterface)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceReaderInterface_RemoteSKIConnected_Call) Return() *ServiceReaderInterface_RemoteSKIConnected_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServiceReaderInterface_RemoteSKIConnected_Call) RunAndReturn(run func(service api.ServiceInterface, ski string)) *ServiceReaderInterface_RemoteSKIConnected_Call {
	_c.Run(run)
	return _c
}

// RemoteSKIDisconnected provides a mock function for the type ServiceReaderInterface
func (_mock *ServiceReaderInterface) RemoteSKIDisconnected(service api.ServiceInterface, ski string) {
	_mock.Called(service, ski)
	return
}

// ServiceReaderInterface_RemoteSKIDisconnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteSKIDisconnected'
type ServiceReaderInterface_RemoteSKIDisconnected_Call struct {
	*mock.Call
}

// RemoteSKIDisconnected is a helper method to define mock.On call
//   - service api.ServiceInterface
//   - ski string
func (_e *ServiceReaderInterface_Expecter) RemoteSKIDisconnected(service interface{}, ski interface{}) *ServiceReaderInterface_RemoteSKIDisconnected_Call {
	return &ServiceReaderInterface_RemoteSKIDisconnected_Call{Call: _e.mock.On("RemoteSKIDisconnected", service, ski)}
}

func (_c *ServiceReaderInterface_RemoteSKIDisconnected_Call) Run(run func(service api.ServiceInterface, ski string)) *ServiceReaderInterface_RemoteSKIDisconnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceInterface
		if args[0] != nil {
			arg0 = args[0].(api.ServiceInterface)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceReaderInterface_RemoteSKIDisconnected_Call) Return() *ServiceReaderInterface_RemoteSKIDisconnected_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServiceReaderInterface_RemoteSKIDisconnected_Call) RunAndReturn(run func(service api.ServiceInterface, ski string)) *ServiceReaderInterface_RemoteSKIDisconnected_Call {
	_c.Run(run)
	return _c
}

// ServicePairingDetailUpdate provides a mock function for the type ServiceReaderInterface
func (_mock *ServiceReaderInterface) ServicePairingDetailUpdate(ski string, detail *api0.ConnectionStateDetail) {
	_mock.Called(ski, detail)
	return
}

// ServiceReaderInterface_ServicePairingDetailUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServicePairingDetailUpdate'
type ServiceReaderInterface_ServicePairingDetailUpdate_Call struct {
	*mock.Call
}

// ServicePairingDetailUpdate is a helper method to define mock.On call
//   - ski string
//   - detail *api0.ConnectionStateDetail
func (_e *ServiceReaderInterface_Expecter) ServicePairingDetailUpdate(ski interface{}, detail interface{}) *ServiceReaderInterface_ServicePairingDetailUpdate_Call {
	return &ServiceReaderInterface_ServicePairingDetailUpdate_Call{Call: _e.mock.On("ServicePairingDetailUpdate", ski, detail)}
}

func (_c *ServiceReaderInterface_ServicePairingDetailUpdate_Call) Run(run func(ski string, detail *api0.ConnectionStateDetail)) *ServiceReaderInterface_ServicePairingDetailUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *api0.ConnectionStateDetail
		if args[1] != nil {
			arg1 = args[1].(*api0.ConnectionStateDetail)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceReaderInterface_ServicePairingDetailUpdate_Call) Return() *ServiceReaderInterface_ServicePairingDetailUpdate_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServiceReaderInterface_ServicePairingDetailUpdate_Call) RunAndReturn(run func(ski string, detail *api0.ConnectionStateDetail)) *ServiceReaderInterface_ServicePairingDetailUpdate_Call {
	_c.Run(run)
	return _c
}

// ServiceShipIDUpdate provides a mock function for the type ServiceReaderInterface
func (_mock *ServiceReaderInterface) ServiceShipIDUpdate(ski string, shipdID string) {
	_mock.Called(ski, shipdID)
	return
}

// ServiceReaderInterface_ServiceShipIDUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceShipIDUpdate'
type ServiceReaderInterface_ServiceShipIDUpdate_Call struct {
	*mock.Call
}

// ServiceShipIDUpdate is a helper method to define mock.On call
//   - ski string
//   - shipdID string
func (_e *ServiceReaderInterface_Expecter) ServiceShipIDUpdate(ski interface{}, shipdID interface{}) *ServiceReaderInterface_ServiceShipIDUpdate_Call {
	return &ServiceReaderInterface_ServiceShipIDUpdate_Call{Call: _e.mock.On("ServiceShipIDUpdate", ski, shipdID)}
}

func (_c *ServiceReaderInterface_ServiceShipIDUpdate_Call) Run(run func(ski string, shipdID string)) *ServiceReaderInterface_ServiceShipIDUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceReaderInterface_ServiceShipIDUpdate_Call) Return() *ServiceReaderInterface_ServiceShipIDUpdate_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServiceReaderInterface_ServiceShipIDUpdate_Call) RunAndReturn(run func(ski string, shipdID string)) *ServiceReaderInterface_ServiceShipIDUpdate_Call {
	_c.Run(run)
	return _c
}

// VisibleRemoteServicesUpdated provides a mock function for the type ServiceReaderInterface
func (_mock *ServiceReaderInterface) VisibleRemoteServicesUpdated(service api.ServiceInterface, entries []api0.RemoteService) {
	_mock.Called(service, entries)
	return
}

// ServiceReaderInterface_VisibleRemoteServicesUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisibleRemoteServicesUpdated'
type ServiceReaderInterface_VisibleRemoteServicesUpdated_Call struct {
	*mock.Call
}

// VisibleRemoteServicesUpdated is a helper method to define mock.On call
//   - service api.ServiceInterface
//   - entries []api0.RemoteService
func (_e *ServiceReaderInterface_Expecter) VisibleRemoteServicesUpdated(service interface{}, entries interface{}) *ServiceReaderInterface_VisibleRemoteServicesUpdated_Call {
	return &ServiceReaderInterface_VisibleRemoteServicesUpdated_Call{Call: _e.mock.On("VisibleRemoteServicesUpdated", service, entries)}
}

func (_c *ServiceReaderInterface_VisibleRemoteServicesUpdated_Call) Run(run func(service api.ServiceInterface, entries []api0.RemoteService)) *ServiceReaderInterface_VisibleRemoteServicesUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ServiceInterface
		if args[0] != nil {
			arg0 = args[0].(api.ServiceInterface)
		}
		var arg1 []api0.RemoteService
		if args[1] != nil {
			arg1 = args[1].([]api0.RemoteService)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceReaderInterface_VisibleRemoteServicesUpdated_Call) Return() *ServiceReaderInterface_VisibleRemoteServicesUpdated_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServiceReaderInterface_VisibleRemoteServicesUpdated_Call) RunAndReturn(run func(service api.ServiceInterface, entries []api0.RemoteService)) *ServiceReaderInterface_VisibleRemoteServicesUpdated_Call {
	_c.Run(run)
	return _c
}
